### ISSUE TITLE
Script pour récupérer les liens iCal d'hyperplanning.

### ISSUE THREAD

**Issue by dannywillems** [UMONS-Cercle-Informatique/superplanning-backend#1]

**Comment by DocSkellington** [comment]
Petit rapport d'avancement:
- Le script charge la page et clique sur les boutons.
- Le problème est que le bouton pour charger la fenêtre pop-up avec le lien  iCal n'est pas toujours cliquable.

**Comment by dannywillems** [comment]
> Le problème est que le bouton pour charger la fenêtre pop-up avec le lien iCal n'est pas toujours cliquable.

:laughing:
